service: aws-node-scheduled-cron

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  environment:
    APTOS_KEY: ${ssm:/betos/test/aptos_key}
    BETOS_ADDRESS: "0x57c21eeb2fd33f64acf8fb54e53783c04579cac5048adec5de00ea95119ebcd7"

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: cron(0/5 * * * ? *)
