service: aws-node-scheduled-cron

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  environment:
    APTOS_KEY: ${ssm:/betos/test/aptos_key}

functions:
  rateHandlerMain:
    handler: handler.run
    events:
      - schedule: cron(0 0,6,12,18 * * ? *) # every 6 hour
    environment:
      BETOS_ADDRESS: "0xb7819e2435c024bd2a84f7527e6b752882a38a0f8835542fa893ac5f511d58a4"
      NETWORK: "mainnet"
  rateHandlerTest:
    handler: handler.run
    events:
      - schedule: cron(0/10 * * * ? *) # every 10 minute
    environment:
      BETOS_ADDRESS: "0x2767545a8d72f4856540d91c6e5b97acbd37380e5d65fb3a11c18c218bbfde12"
      NETWORK: "testnet"
