# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  schedule:
     - cron: "*/5 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: Install dependencies
      run: | 
        cd scripts
        yarn install

    - name: Test unit
      run: yarn run ts-node execute.ts --action execute
